worldname: Volans
firespread_disabled: true
cancel_natural_spawns: true

weathermachines:
  global:
    rain_chance: 0.5
    minimum_rain_duration: 3h
    areas:
      biomes:
       - GLOBAL
daytime_modifier:
  global:
    dayspeed: 0.33
    starting_time: 0
    areas:
      biomes:
       - GLOBAL

monster:
 normalselection:
  updatetime: 15s
  areas:
    biomes:
     - EXTREME_HILLS
     - MUSHROOM_ISLAND
  mobconfig:
   spiders:
     type: SPIDER 
     spawn_chance: 0.0444
     identifier: spiders
     maximum_light_level: 7
   creepers:
     type: CREEPER 
     spawn_chance: 0.0444
     identifier: creepers
     maximum_light_level: 7
   skeletons:
     type: SKELETON
     spawn_chance: 0.0444
     identifier: skeleton
     maximum_light_level: 7
   zombies:
     type: ZOMBIE
     spawn_chance: 0.0444
     identifier: zombie
     maximum_light_level: 7
   witches:
     type: WITCH
     spawn_chance: 0.0222
     identifier: witches
     maximum_light_level: 7
   silverfish:
     type: SILVERFISH
     spawn_chance: 0.0222
     identifier: silverfish
     maximum_light_level: 7
   sheep:
     type: SHEEP
     spawn_chance: 0.03
     identifier: sheep
     minimum_light_level: 8
     blocks_to_spawn_on:
      - DIRT
      - GRASS
      - MYCELIUM
   bat:
     type: BAT
     spawn_chance: 0.03
     identifier: bat
     maximum_light_level: 7
     blocks_to_spawn_on:
      - STONE
monster:
 mushroomisland:
  updatetime: 15s
  areas:
    biomes:
     - MUSHROOM_ISLAND
  mobconfig:
   mooshroom:
     type: MUSHROOM_COW
     spawn_chance: 0.03
     identifier: mooshroom
     minimum_light_level: 8
     blocks_to_spawn_on:
      - DIRT
      - GRASS
      - MYCELIUM
